### ISSUE TITLE
Error during installation of release 1.5.1 and 1.5.7

### ISSUE THREAD

**Issue by yeastbeast** [local-minimum/scanomatic#115]
Hi,
I consistently get this error when trying to install on Ubuntu 16.04 with release 1.5.1 and 1.5.7.
1.4 works fine though.

Traceback (most recent call last):
  File "setup.py", line 185, in <module>
    update_init_file(do_branch=True, do_version=False)
  File "/home/stephan/scanomatic-1.5.1/setup_tools.py", line 102, in update_init_file
    data = source.get_source_information(True, force_location=cur_dir)
  File "/home/stephan/scanomatic-1.5.1/scanomatic/io/source.py", line 49, in get_source_information
    data = _load_source_information()
  File "/home/stephan/scanomatic-1.5.1/scanomatic/io/source.py", line 33, in _load_source_information
    with open(Paths().source_location_file, 'r') as fh:
  File "/home/stephan/scanomatic-1.5.1/scanomatic/generics/singleton.py", line 33, in __init__
    self.__one_init__(*args, **kwargs)
  File "/home/stephan/scanomatic-1.5.1/scanomatic/io/paths.py", line 37, in __one_init__
    raise InvalidRoot(self.root)
scanomatic.io.paths.InvalidRoot: /home/stephan/.scan-o-matic

**Comment by local-minimum** [comment]
Oh, if you for now just create that directory `/home/stephan/.scan-o-matic`, I'll try to make a fix tomorrow, but we'll have a bit of version issue due to now only working on v2.x so perhaps the best solution for you it to create the missing folders until installation completes.

**Comment by local-minimum** [comment]
This is now solved as of `v2.0.4` but it will be some time before it is included in any release so I recommend creating a folder `.scan-o-matic` in your home folder and then setup should work nicely.
